version: '3'

services:
  postgis:
    image: 'postgis/postgis:12-master'
    volumes:
      - 'postgis:/var/lib/postgresql/data'
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust

  api:
    depends_on:
      - 'postgis'
    build: ./backend
    command: bash
    environment: 
      - RAILS_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - './backend:/find_my_coffee'
      - 'gems:/gems'
    tty: true

  web:
    depends_on:
      - 'api'
    image: node:14
    ports:
      - 3001:3000
    volumes:
      - ./frontend-web:/find_my_coffee_web
    working_dir: /find_my_coffee_web
    command: bash start
    stdin_open: true
    # tty: true

volumes:
  postgis:
  gems: